name-template: "v$RESOLVED_VERSION ğŸš€"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "âœ¨ Features"
    labels:
      - "feat"
  - title: "ğŸ› Bug Fixes"
    labels:
      - "fix"
  - title: "ğŸ§° Maintenance"
    label:
      - "refactor"
      - "test"
      - "ci"
      - "build"
      - "style"
      - "chore"
      - "dependencies"
  - title: "ğŸ“„ Documentation"
    label:
      - "docs"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "ğŸš€ major"
  minor:
    labels:
      - "ğŸš€ minor"
      - "feat"
  patch:
    labels:
      - "ğŸš€ patch"
  default: patch
template: |
  ## What's Changed

  $CHANGES
footer: |

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
